### ISSUE TITLE
Targeted refresh fails to save with `[TypeError]: can't cast Hash` failure

### ISSUE THREAD

**Issue by agrare** [ManageIQ/manageiq-providers-azure#400]
```
[----] I, [2020-06-22T05:41:01.202632 #4738:2ae52a6d3960]  INFO -- : Q-task_id([r16_miq_provision_16]) MIQ(ManageIQ::Providers::Azure::CloudManager::Refresher#refresh) Refreshing all targets...
[----] I, [2020-06-22T05:41:01.202787 #4738:2ae52a6d3960]  INFO -- : Q-task_id([r16_miq_provision_16]) MIQ(ManageIQ::Providers::Azure::CloudManager::Refresher#refresh) EMS: [MSAzure], id: [255] Refreshing target
s for EMS...
[----] I, [2020-06-22T05:41:01.202937 #4738:2ae52a6d3960]  INFO -- : Q-task_id([r16_miq_provision_16]) MIQ(ManageIQ::Providers::Azure::CloudManager::Refresher#refresh) EMS: [MSAzure], id: [255]   InventoryRefres
h::TargetCollection [Collection of 1 targets] id [Collection of targets with id: [{:ems_ref=>{:subscription_id=>"0e0a4287-8719-4849-bb0b-5242e4507709", :vm_resource_group=>"infra-mgmt-auto-test", :type=>"microso
ft.compute/virtualmachines", :vm_name=>"test-ci-t1vp"}}]]
[----] I, [2020-06-22T05:41:13.493839 #4738:2ae52a6d3960]  INFO -- : Q-task_id([r16_miq_provision_16]) Exception in realtime_block :ems_refresh - Timings: {:collect_inventory_for_targets=>12.290756225585938, :em
s_refresh=>12.290783166885376}
[----] E, [2020-06-22T05:41:13.494053 #4738:2ae52a6d3960] ERROR -- : Q-task_id([r16_miq_provision_16]) MIQ(ManageIQ::Providers::Azure::CloudManager::Refresher#refresh) EMS: [MSAzure], id: [255] Refresh failed
[----] E, [2020-06-22T05:41:13.494187 #4738:2ae52a6d3960] ERROR -- : Q-task_id([r16_miq_provision_16]) [TypeError]: can't cast Hash  Method:[block (2 levels) in <class:LogProxy>]
[----] E, [2020-06-22T05:41:13.494260 #4738:2ae52a6d3960] ERROR -- : Q-task_id([r16_miq_provision_16]) /opt/IBM/infrastructure-management-gemset/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/ab
stract/quoting.rb:34:in `rescue in type_cast'
[----] E, [2020-06-22T05:41:13.494331 #4738:2ae52a6d3960] ERROR -- : Q-task_id([r16_miq_provision_16]) MIQ(ManageIQ::Providers::Azure::CloudManager::Refresher#refresh) EMS: [MSAzure], id: [255] Unable to perform
 refresh for the following targets:
[----] E, [2020-06-22T05:41:13.494414 #4738:2ae52a6d3960] ERROR -- : Q-task_id([r16_miq_provision_16]) MIQ(ManageIQ::Providers::Azure::CloudManager::Refresher#refresh)  --- InventoryRefresh::TargetCollection [Co
llection of 1 targets] id [Collection of targets with id: [{:ems_ref=>{:subscription_id=>"0e0a4287-8719-4849-bb0b-5242e4507709", :vm_resource_group=>"infra-mgmt-auto-test", :type=>"microsoft.compute/virtualmachi
nes", :vm_name=>"test-ci-t1vp"}}]]
[----] I, [2020-06-22T05:41:13.511627 #4738:2ae52a6d3960]  INFO -- : Q-task_id([r16_miq_provision_16]) MIQ(ManageIQ::Providers::Azure::CloudManager::Refresher#refresh) Refreshing all targets...Complete
[----] E, [2020-06-22T05:41:13.511874 #4738:2ae52a6d3960] ERROR -- : Q-task_id([r16_miq_provision_16]) MIQ(MiqQueue#deliver) Message id: [549090], Error: [can't cast Hash]
[----] E, [2020-06-22T05:41:13.511981 #4738:2ae52a6d3960] ERROR -- : Q-task_id([r16_miq_provision_16]) [ManageIQ::Providers::BaseManager::Refresher::PartialRefreshError]: can't cast Hash  Method:[block (2 levels
) in <class:LogProxy>]
[----] E, [2020-06-22T05:41:13.512083 #4738:2ae52a6d3960] ERROR -- : Q-task_id([r16_miq_provision_16]) /var/www/miq/vmdb/app/models/manageiq/providers/base_manager/refresher.rb:67:in `refresh'
```

**Comment by agrare** [comment]
I wasn't able to get a better backtrace than this but it looks like any targeted refresh of an instance might hit this

**Comment by djberg96** [comment]
@agrare I've not seen this. How/when did you encounter it?

**Comment by agrare** [comment]
Saw it in the logs on an appliance

**Comment by djberg96** [comment]
@agrare Is that coming from the AR adapter? I can see `/opt/IBM/infrastructure-management-gemset/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/ab` but it cuts off.

Don't suppose you have the full backtrace do you?

**Comment by djberg96** [comment]
So here's the method in question: https://github.com/rails/rails/blob/5-2-stable/activerecord/lib/active_record/connection_adapters/abstract/quoting.rb#L21-L35

Are they using postgres as the database? Is this db2 by any chance?

**Comment by agrare** [comment]
@djberg96 this was a normal MIQ appliance so it was our postgres database.  Usually this happens when the parser is trying to set an invalid value to a column during targeted refresh so it isn't really related to the low-level activerecord code at all

We aren't able to tell which column from the error but if you're looking to try to reproduce the list of targets it was refreshing would be a place to start:
```
[----] E, [2020-06-22T05:41:13.494414 #4738:2ae52a6d3960] ERROR -- : Q-task_id([r16_miq_provision_16]) MIQ(ManageIQ::Providers::Azure::CloudManager::Refresher#refresh)  --- InventoryRefresh::TargetCollection [Collection of 1 targets] id [Collection of targets with id: [{:ems_ref=>{:subscription_id=>"0e0a4287-8719-4849-bb0b-5242e4507709", :vm_resource_group=>"infra-mgmt-auto-test", :type=>"microsoft.compute/virtualmachines", :vm_name=>"test-ci-t1vp"}}]]
```

**Comment by djberg96** [comment]
Without more info I'm afraid there's little I can do. All I can tell you is that there's nothing special about the VM name or resource group name. I recreated both just to double check, and it worked fine, so it's some other property.

**Comment by agrare** [comment]
A community user has been hitting this reliably and we have a better backtrace, the error isn't on save it is actually querying for related inventory early in the targeted collection:

```
[----] I, [2022-08-02T18:05:50.539748 #344:95b0]  INFO -- evm: MIQ(MiqQueue.get) Message id: [2277], Zone: [default], Role: [ems_inventory], Server: [], MiqTask id: [], Handler id: [MiqWorker 48], Ident: [ems_5], Target id: [], Instance id: [], Task id: [], Command: [EmsRefresh.refresh], Timeout: [7200], Priority: [100], State: [dequeue], Deliver On: [], Data: [1 bytes], Args: [], Dequeued in: [2.7472328] seconds
[----] I, [2022-08-02T18:05:50.541667 #344:95b0]  INFO -- evm: Q-task_id([r6_miq_provision_12]) MIQ(MiqQueue#deliver) Message id: [2277], Delivering...
[----] I, [2022-08-02T18:05:50.565389 #344:95b0]  INFO -- evm: Q-task_id([r6_miq_provision_12]) MIQ(ManageIQ::Providers::Azure::CloudManager::Refresher#refresh) Refreshing all targets...
[----] I, [2022-08-02T18:05:50.567245 #344:95b0]  INFO -- evm: Q-task_id([r6_miq_provision_12]) MIQ(ManageIQ::Providers::Azure::CloudManager::Refresher#refresh) EMS: [Azure], id: [5] Refreshing targets for EMS...
[----] I, [2022-08-02T18:05:50.568466 #344:95b0]  INFO -- evm: Q-task_id([r6_miq_provision_12]) MIQ(ManageIQ::Providers::Azure::CloudManager::Refresher#refresh) EMS: [Azure], id: [5]   InventoryRefresh::TargetCollection [Collection of 1 targets] id [Collection of targets with id: [{:ems_ref=>{:subscription_id=>"123456789", :vm_resource_group=>"cloud-shell-storage-              centralindia", :type=>"microsoft.compute/virtualmachines", :vm_name=>"Ubuntu004"}}]]
[----] E, [2022-08-02T18:06:06.254184 #344:95b0] ERROR -- evm: Q-task_id([r6_miq_provision_12]) MIQ(ManageIQ::Providers::Azure::CloudManager::Refresher#refresh) EMS: [Azure], id: [5] Refresh failed
[----] E, [2022-08-02T18:06:06.254498 #344:95b0] ERROR -- evm: Q-task_id([r6_miq_provision_12]) [TypeError]: can't cast Hash  Method:[block (2 levels) in <class:LogProxy>]
[----] E, [2022-08-02T18:06:06.254827 #344:95b0] ERROR -- evm: Q-task_id([r6_miq_provision_12]) /opt/manageiq/manageiq-gemset/gems/activerecord-6.0.5.1/lib/active_record/connection_adapters/abstract/quoting.rb:34:in `rescue in type_cast'
/opt/manageiq/manageiq-gemset/gems/activerecord-6.0.5.1/lib/active_record/connection_adapters/abstract/quoting.rb:24:in `type_cast'
/opt/manageiq/manageiq-gemset/gems/activerecord-6.0.5.1/lib/active_record/connection_adapters/abstract/quoting.rb:203:in `block in type_casted_binds'
/opt/manageiq/manageiq-gemset/gems/activerecord-6.0.5.1/lib/active_record/connection_adapters/abstract/quoting.rb:203:in `map'
/opt/manageiq/manageiq-gemset/gems/activerecord-6.0.5.1/lib/active_record/connection_adapters/abstract/quoting.rb:203:in `type_casted_binds'
/opt/manageiq/manageiq-gemset/gems/activerecord-6.0.5.1/lib/active_record/connection_adapters/postgresql_adapter.rb:672:in `exec_no_cache'
/opt/manageiq/manageiq-gemset/gems/activerecord-6.0.5.1/lib/active_record/connection_adapters/postgresql_adapter.rb:656:in `execute_and_clear'
/opt/manageiq/manageiq-gemset/gems/activerecord-6.0.5.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in `exec_query'
/opt/manageiq/manageiq-gemset/gems/activerecord-6.0.5.1/lib/active_record/connection_adapters/abstract/database_statements.rb:489:in `select'
/opt/manageiq/manageiq-gemset/gems/activerecord-6.0.5.1/lib/active_record/connection_adapters/abstract/database_statements.rb:70:in `select_all'
/opt/manageiq/manageiq-gemset/gems/activerecord-6.0.5.1/lib/active_record/connection_adapters/abstract/query_cache.rb:107:in `select_all'
/opt/manageiq/manageiq-gemset/gems/activerecord-6.0.5.1/lib/active_record/querying.rb:46:in `find_by_sql'
/opt/manageiq/manageiq-gemset/gems/activerecord-6.0.5.1/lib/active_record/relation.rb:824:in `block in exec_queries'
/opt/manageiq/manageiq-gemset/gems/activerecord-6.0.5.1/lib/active_record/relation.rb:842:in `skip_query_cache_if_necessary'
/opt/manageiq/manageiq-gemset/gems/activerecord-6.0.5.1/lib/active_record/relation.rb:811:in `exec_queries'
/opt/manageiq/manageiq-gemset/gems/activerecord-6.0.5.1/lib/active_record/association_relation.rb:36:in `exec_queries'
/opt/manageiq/manageiq-gemset/gems/activerecord-6.0.5.1/lib/active_record/relation.rb:626:in `load'
/opt/manageiq/manageiq-gemset/gems/activerecord-6.0.5.1/lib/active_record/relation.rb:250:in `records'
/opt/manageiq/manageiq-gemset/gems/activerecord-6.0.5.1/lib/active_record/relation/delegation.rb:88:in `each'
/opt/manageiq/manageiq-gemset/bundler/gems/manageiq-providers-azure-622e43171bad/app/models/manageiq/providers/azure/inventory/collector/target_collection.rb:519:in `infer_related_vm_ems_refs_db!'
/opt/manageiq/manageiq-gemset/bundler/gems/manageiq-providers-azure-622e43171bad/app/models/manageiq/providers/azure/inventory/collector/target_collection.rb:420:in `infer_related_ems_refs!'
/opt/manageiq/manageiq-gemset/bundler/gems/manageiq-providers-azure-622e43171bad/app/models/manageiq/providers/azure/inventory/collector/target_collection.rb:8:in `initialize'
/var/www/miq/vmdb/app/models/manageiq/providers/inventory.rb:11:in `new'
/var/www/miq/vmdb/app/models/manageiq/providers/inventory.rb:11:in `build'
/var/www/miq/vmdb/app/models/manageiq/providers/base_manager/refresher.rb:116:in `block in collect_inventory_for_targets'
/var/www/miq/vmdb/app/models/manageiq/providers/base_manager/refresher.rb:115:in `map'
/var/www/miq/vmdb/app/models/manageiq/providers/base_manager/refresher.rb:115:in `collect_inventory_for_targets'
/var/www/miq/vmdb/app/models/manageiq/providers/base_manager/refresher.rb:87:in `block in refresh_targets_for_ems'
/opt/manageiq/manageiq-gemset/gems/more_core_extensions-4.4.0/lib/more_core_extensions/core_ext/benchmark/realtime_store.rb:20:in `realtime_store'
/opt/manageiq/manageiq-gemset/gems/more_core_extensions-4.4.0/lib/more_core_extensions/core_ext/benchmark/realtime_store.rb:56:in `realtime_block'
/var/www/miq/vmdb/app/models/manageiq/providers/base_manager/refresher.rb:86:in `refresh_targets_for_ems'
/var/www/miq/vmdb/app/models/manageiq/providers/base_manager/refresher.rb:41:in `block (2 levels) in refresh'
/opt/manageiq/manageiq-gemset/gems/more_core_extensions-4.4.0/lib/more_core_extensions/core_ext/benchmark/realtime_store.rb:20:in `realtime_store'
/opt/manageiq/manageiq-gemset/gems/more_core_extensions-4.4.0/lib/more_core_extensions/core_ext/benchmark/realtime_store.rb:62:in `realtime_block'
/var/www/miq/vmdb/app/models/manageiq/providers/base_manager/refresher.rb:41:in `block in refresh'
/var/www/miq/vmdb/app/models/manageiq/providers/base_manager/refresher.rb:31:in `each'
/var/www/miq/vmdb/app/models/manageiq/providers/base_manager/refresher.rb:31:in `refresh'
/var/www/miq/vmdb/app/models/manageiq/providers/base_manager/refresher.rb:11:in `refresh'
/var/www/miq/vmdb/app/models/ems_refresh.rb:71:in `block in refresh'
/var/www/miq/vmdb/app/models/ems_refresh.rb:70:in `each'
/var/www/miq/vmdb/app/models/ems_refresh.rb:70:in `refresh'
```
