### ISSUE TITLE
SSA failure during perform_metadata_scan

### ISSUE THREAD

**Issue by spicoli9000** [ManageIQ/manageiq-providers-azure#445]
Error with SSA running docker versions: manageiq/manageiq:jansa-3, latest-jansa, latest-kasparov.
SSA worked on ivanchuk-8

**Logs from testing with latest-jansa:**
`
{"@timestamp":"2021-03-08T19:42:23.140337 ","hostname":"a2569443fbda","pid":3970,"tid":"2ac3751af94c","level":"debug","message":"Q-task_id([job_dispatcher]) MIQ(ManageIQ::Providers::Azure::CloudManager::Vm#perform_metadata_scan) name: ansible-vm3 (templat
e = false)"}
{"@timestamp":"2021-03-08T19:42:23.140452 ","hostname":"a2569443fbda","pid":3970,"tid":"2ac3751af94c","level":"debug","message":"Q-task_id([job_dispatcher]) MIQ(ManageIQ::Providers::Azure::CloudManager::Vm#perform_metadata_scan) jstdebug2: set vm_args res
ource_group.name"}
{"@timestamp":"2021-03-08T19:42:23.179371 ","hostname":"a2569443fbda","pid":3970,"tid":"2ac3751af94c","level":"debug","message":"Q-task_id([job_dispatcher]) MIQ(ManageIQ::Providers::Azure::CloudManager::Vm#perform_metadata_scan) jstdebug2: set vm_args ost.scanData ost: #\u003cOpenStruct args=[\"eastus\", {\"ems\"=\u003e{\"ems\"=\u003e{:hostname=\u003enil, :ipaddress=\u003enil, :username=\u003e\"4f7b1e0f-8d60-4c7c-8978-8e4c62fa7d77\", :password=\u003e\"v2:{5yNsUngLLdXAahqvhCCQa6I/6Bp9s7Ln7iPOJApeyx/FHbBsdEc5K4euUQJJRfBtOSAb6smsj9R62ecNEHmIUOW+BLfXPu/riflLqT25VWI=}\", :class_name=\u003e\"ManageIQ::Providers::Azure::CloudManager\"}, \"connect_to\"=\u003e\"host\"}, \"vmScanProfiles\"=\u003e[]}], method_name=\"scan_metadata\", vm_guid=\"7ddea001-3b3b-4c10-a8f9-cd60c8d98542\", category=\"vmconfig,accounts,software,services,system\", taskid=\"4edcda4f-b853-47f0-91ce-b7987fab5c0a\", target_id=3, target_type=\"VmOrTemplate\", scanData={\"ems\"=\u003e{\"ems\"=\u003e{:hostname=\u003enil, :ipaddress=\u003enil, :username=\u003e\"4f7b1e0f-8d60-4c7c-8978-8e4c62fa7d77\", :password=\u003e\"v2:{5yNsUngLLdXAahqvhCCQa6I/6Bp9s7Ln7iPOJApeyx/FHbBsdEc5K4euUQJJRfBtOSAb6smsj9R62ecNEHmIUOW+BLfXPu/riflLqT25VWI=}\", :class_name=\u003e\"ManageIQ::Providers::Azure::CloudManager\"}, \"connect_to\"=\u003e\"host\"}, \"vmScanProfiles\"=\u003e[]}, jobid=9, config=#\u003cOpenStruct vmdb=true, forceFleeceDefault=true, capabilities={:vixDisk=\u003efalse}\u003e\u003e"}
{"@timestamp":"2021-03-08T19:42:23.180329 ","hostname":"a2569443fbda","pid":3970,"tid":"2ac3751af94c","level":"err","message":"Q-task_id([job_dispatcher]) MIQ(MiqServer#scan_metadata) undefined method `[]' for nil:NilClass"}
{"@timestamp":"2021-03-08T19:42:23.180543 ","hostname":"a2569443fbda","pid":3970,"tid":"2ac3751af94c","level":"debug","message":"Q-task_id([job_dispatcher]) [NoMethodError]: undefined method `[]' for nil:NilClass  Method:[block (2 levels) in \u003cclass:LogProxy\u003e]"}
{"@timestamp":"2021-03-08T19:42:23.180652 ","hostname":"a2569443fbda","pid":3970,"tid":"2ac3751af94c","level":"debug","message":"Q-task_id([job_dispatcher]) /opt/manageiq/manageiq-gemset/bundler/gems/manageiq-providers-azure-e7914f85e845/app/models/manageiq/providers/azure/cloud_manager/vm_or_template_shared/scanning.rb:47:in `perform_metadata_scan'\n/var/www/miq/vmdb/app/models/miq_server/server_smart_proxy.rb:95:in `scan_metadata'\n/var/www/miq/vmdb/app/models/miq_queue.rb:484:in `block in dispatch_method'\n/usr/share/ruby/timeout.rb:93:in `block in timeout'\n/usr/share/ruby/timeout.rb:33:in `block in catch'\n/usr/share/ruby/timeout.rb:33:in `catch'\n/usr/share/ruby/timeout.rb:33:in `catch'\n/usr/share/ruby/timeout.rb:108:in `timeout'\n/var/www/miq/vmdb/app/models/miq_queue.rb:482:in `dispatch_method'\n/var/www/miq/vmdb/app/models/miq_queue.rb:459:in `block in deliver'\n/var/www/miq/vmdb/app/models/user.rb:324:in `with_user_group'\n/var/www/miq/vmdb/app/models/miq_queue.rb:459:in `deliver'\n/var/www/miq/vmdb/app/models/miq_queue_worker_base/runner.rb:80:in `deliver_queue_message'\n/var/www/miq/vmdb/app/models/miq_queue_worker_base/runner.rb:104:in `deliver_message'\n/var/www/miq/vmdb/app/models/miq_queue_worker_base/runner.rb:122:in `block in do_work'\n/var/www/miq/vmdb/app/models/miq_queue_worker_base/runner.rb:118:in `loop'\n/var/www/miq/vmdb/app/models/miq_queue_worker_base/runner.rb:118:in `do_work'\n/var/www/miq/vmdb/app/models/miq_smart_proxy_worker/runner.rb:71:in `do_work'\n/var/www/miq/vmdb/app/models/miq_worker/runner.rb:256:in `block in do_work_loop'\n/var/www/miq/vmdb/app/models/miq_worker/runner.rb:253:in `loop'\n/var/www/miq/vmdb/app/models/miq_worker/runner.rb:253:in `do_work_loop'\n/var/www/miq/vmdb/app/models/miq_worker/runner.rb:113:in `run'\n/var/www/miq/vmdb/app/models/miq_worker/runner.rb:95:in `start'\n/var/www/miq/vmdb/lib/workers/bin/run_single_worker.rb:124:in `\u003cmain\u003e'"}
{"@timestamp":"2021-03-08T19:42:23.239065 ","hostname":"a2569443fbda","pid":3970,"tid":"2ac3751af94c","level":"info","message":"Q-task_id([job_dispatcher]) MIQ(ManageIQ::Providers::Azure::CloudManager::Scanning::Job#scanning) ."}
{"@timestamp":"2021-03-08T19:42:23.862354 ","hostname":"a2569443fbda","pid":3970,"tid":"2ac3751af94c","level":"info","message":"Q-task_id([job_dispatcher]) MiqAeEvent.build_evm_event \u003e\u003e event=\u003c\"vm_scan_abort\"\u003e inputs=\u003c{:vm=\u003e#\u003cManageIQ::Providers::Azure::CloudManager::Vm id: 3, vendor: \"azure\", format: nil, version: nil, name: \"ansible-vm3\", description: nil, location: \"eastus\", config_xml: nil, autostart: nil, host_id: nil, last_sync_on: nil, created_on: \"2021-03-08 18:05:20\", updated_on: \"2021-03-08 19:41:46\", storage_id: nil, guid: \"7ddea001-3b3b-4c10-a8f9-cd60c8d98542\", ems_id: 2, last_scan_on: nil, last_scan_attempt_on: \"2021-03-08 19:41:46\", uid_ems: \"7cde102a-5170-451c-846b-354f7b677b95/myapp-rg/micr...\", retires_on: nil, retired: nil, boot_time: nil, tools_status: nil, standby_action: nil, power_state: \"off\", state_changed_on: \"2021-03-08 18:05:20\", previous_state: nil, connection_state: \"connected\", last_perf_capture_on: nil, registered: nil, busy: nil, smart: nil, memory_reserve: nil, memory_reserve_expand: nil, memory_limit: nil, memory_shares: nil, memory_shares_level: nil, cpu_reserve: nil, cpu_reserve_expand: nil, cpu_limit: nil, cpu_shares: nil, cpu_shares_level: nil, cpu_affinity: nil, ems_created_on: nil, template: false, evm_owner_id: nil, miq_group_id: 1, linked_clone: nil, fault_tolerance: nil, type: \"ManageIQ::Providers::Azure::CloudManager::Vm\", ems_ref: \"7cde102a-5170-451c-846b-354f7b677b95/myapp-rg/micr...\", ems_cluster_id: nil, retirement_warn: nil, retirement_last_warn: nil, vnc_port: nil, flavor_id: 41, availability_zone_id: 1, cloud: true, retirement_state: nil, cloud_network_id: nil, cloud_subnet_id: nil, cloud_tenant_id: nil, raw_power_state: \"VM deallocated\", publicly_available: nil, orchestration_stack_id: nil, retirement_requester: nil, tenant_id: 1, resource_group_id: 1, deprecated: nil, storage_profile_id: nil, cpu_hot_add_enabled: nil, cpu_hot_remove_enabled: nil, memory_hot_add_enabled: nil, memory_hot_add_limit: nil, memory_hot_add_increment: nil, hostname: nil, ems_ref_type: nil, restart_needed: nil\u003e, :host=\u003enil, \"MiqEvent::miq_event\"=\u003e120, :miq_event_id=\u003e120, \"EventStream::event_stream\"=\u003e120, :event_stream_id=\u003e120}\u003e"}
[----] I, [2021-03-08T19:42:24.074953 #6:2b0a43b59960]  INFO -- : MIQ(MiqServer#heartbeat) Heartbeat [2021-03-08 19:42:24 UTC]...
[----] I, [2021-03-08T19:42:24.083893 #6:2b0a43b59960]  INFO -- : MIQ(MiqServer#heartbeat) Heartbeat [2021-03-08 19:42:24 UTC]...Complete
[----] I, [2021-03-08T19:42:24.089479 #6:2b0a43b59960]  INFO -- : MIQ(MiqServer#populate_queue_messages) Fetched 2 miq_queue rows for queue_name=generic, wcount=4, priority=200
[----] I, [2021-03-08T19:42:24.151873 #3970:2ac3751af94c]  INFO -- : Q-task_id([job_dispatcher]) MIQ(MiqQueue.put) Message id: [2800],  id: [], Zone: [default], Role: [automate], Server: [], MiqTask id: [], Ident: [generic], Target id: [], Instance id: [], Task id: [], Command: [MiqAeEngine.deliver], Timeout: [3600], Priority: [20], State: [ready], Deliver On: [], Data: [], Args: [{:object_type=>"ManageIQ::Providers::Azure::CloudManager::Vm", :object_id=>3, :attrs=>{:event_type=>"vm_scan_abort", "VmOrTemplate::vm"=>3, :vm_id=>3, :host=>nil, "MiqEvent::miq_event"=>120, :miq_event_id=>120, "EventStream::event_stream"=>120, :event_stream_id=>120}, :instance_name=>"Event", :user_id=>1, :miq_group_id=>1, :tenant_id=>1, :automate_message=>nil}]
[----] E, [2021-03-08T19:42:24.152050 #3970:2ac3751af94c] ERROR -- : Q-task_id([job_dispatcher]) MIQ(ManageIQ::Providers::Azure::CloudManager::Scanning::Job#process_abort) job aborting, undefined method `[]' for nil:NilClass
`
**Added debug statements to:**
/opt/manageiq/manageiq-gemset/bundler/gems/manageiq-providers-azure-e7914f85e845/app/models/manageiq/providers/azure/cloud_manager/vm_or_template_shared/scanning.rb

`
  def perform_metadata_scan(ost)
    require 'MiqVm/miq_azure_vm'

    vm_args = { :name => name }
    _log.debug("jstdebug2: in perform_metadata_scan")
    _log.debug("name: #{name} (template = #{template})")
    if template
      if managed_image?
        vm_args[:resource_group] = managed_resource_group
        vm_args[:managed_image]  = managed_image_disk_name
      elsif blob_uri
        vm_args[:image_uri] = blob_uri
      else
        vm_args[:image_uri] = uid_ems
      end
    else
      _log.debug("jstdebug2: set vm_args resource_group.name")
      vm_args[:resource_group] = resource_group.name
      #vm_args[:resource_group] = "myapp-rg"
      _log.debug("jstdebug2: set vm_args ost.scanData ost: #{ost}")
      vm_args[:snapshot] = ost.scanData["snapshot"]["name"]
      _log.debug("jstdebug2: vm_args = #{vm_args}")
    end
    _log.debug("jstdebug2: set ost.scantime")
    ost.scanTime = Time.now.utc unless ost.scanTime
    _log.debug("jstdebug2: set armrest")
    armrest      = ext_management_system.connect
`
seems to fail on:
`vm_args[:snapshot] = ost.scanData["snapshot"]["name"]`

ost object in the log:
`{"@timestamp":"2021-03-08T19:42:23.179371 ","hostname":"a2569443fbda","pid":3970,"tid":"2ac3751af94c","level":"debug","message":"Q-task_id([job_dispatcher]) MIQ(ManageIQ::Providers::Azure::CloudManager::Vm#perform_metadata_scan) jstdebug2: set vm_args ost.scanData ost: #\u003cOpenStruct args=[\"eastus\", {\"ems\"=\u003e{\"ems\"=\u003e{:hostname=\u003enil, :ipaddress=\u003enil, :username=\u003e\"4f7b1e0f-8d60-4c7c-8978-8e4c62fa7d77\", :password=\u003e\"v2:{5yNsUngLLdXAahqvhCCQa6I/6Bp9s7Ln7iPOJApeyx/FHbBsdEc5K4euUQJJRfBtOSAb6smsj9R62ecNEHmIUOW+BLfXPu/riflLqT25VWI=}\", :class_name=\u003e\"ManageIQ::Providers::Azure::CloudManager\"}, \"connect_to\"=\u003e\"host\"}, \"vmScanProfiles\"=\u003e[]}], method_name=\"scan_metadata\", vm_guid=\"7ddea001-3b3b-4c10-a8f9-cd60c8d98542\", category=\"vmconfig,accounts,software,services,system\", taskid=\"4edcda4f-b853-47f0-91ce-b7987fab5c0a\", target_id=3, target_type=\"VmOrTemplate\", scanData={\"ems\"=\u003e{\"ems\"=\u003e{:hostname=\u003enil, :ipaddress=\u003enil, :username=\u003e\"4f7b1e0f-8d60-4c7c-8978-8e4c62fa7d77\", :password=\u003e\"v2:{5yNsUngLLdXAahqvhCCQa6I/6Bp9s7Ln7iPOJApeyx/FHbBsdEc5K4euUQJJRfBtOSAb6smsj9R62ecNEHmIUOW+BLfXPu/riflLqT25VWI=}\", :class_name=\u003e\"ManageIQ::Providers::Azure::CloudManager\"}, \"connect_to\"=\u003e\"host\"}, \"vmScanProfiles\"=\u003e[]}, jobid=9, config=#\u003cOpenStruct vmdb=true, forceFleeceDefault=true, capabilities={:vixDisk=\u003efalse}\u003e\u003e"}`

**Comment by Fryguy** [comment]
@chessbyte Could this have been affected by your relatively recent refactoring?  I can't remember when that landed, but this issue is present in >= jansa-3, according to the OP.
