### ISSUE TITLE
Refresh fails with error: "\xEF" from ASCII-8BIT to UTF-8, podified

### ISSUE THREAD

**Issue by evertmulder** [ManageIQ/manageiq-providers-azure#451]
Hi,

when using the Azure provider from ManageIQ Kasparov-1 the refresh is always failing with this error:
`"\xEF" from ASCII-8BIT to UTF-8`. We are using the podified version running on Kubernetes.

I also tried the azure provider on a Jansa appliance. Here the refresh works without issues.
Then I also tried the azure provider on a Kasparov-1 appliance. Here the refresh works without issues.

I'm not sure what would be the difference between the podified and appliance, perhaps the logging configuration `/var/www/miq/vmdb/lib/vmdb/loggers/container_logger.rb:43`?

```
[----] I, [2021-03-30T21:14:17.610988 #7:2b25bdd0597c]  INFO -- : MIQ(ManageIQ::Providers::Azure::Inventory::Collector::CloudManager#collect_inventory) Retrieving Managed Images...
[----] I, [2021-03-30T21:14:17.663854 #7:2b25bdd0597c]  INFO -- : MIQ(ManageIQ::Providers::Azure::Inventory::Collector::CloudManager#collect_inventory) Retrieving Managed Images...Complete - Count [0]
[----] I, [2021-03-30T21:14:17.684629 #7:2b25bdd0597c]  INFO -- : MIQ(ManageIQ::Providers::Azure::Inventory::Collector::CloudManager#collect_inventory) Retrieving Private Images...
[----] E, [2021-03-30T21:14:17.980883 #7:2b25bdd0597c] ERROR -- : MIQ(ManageIQ::Providers::Azure::CloudManager::Refresher#refresh) EMS: [test2], id: [5] Refresh failed
[----] E, [2021-03-30T21:14:17.980991 #7:2b25bdd0597c] ERROR -- : [Encoding::UndefinedConversionError]: "\xEF" from ASCII-8BIT to UTF-8  Method:[block (2 levels) in <class:LogProxy>]
[----] E, [2021-03-30T21:14:17.981067 #7:2b25bdd0597c] ERROR -- : /opt/manageiq/manageiq-gemset/gems/json-2.5.1/lib/json/common.rb:312:in `generate'
/opt/manageiq/manageiq-gemset/gems/json-2.5.1/lib/json/common.rb:312:in `generate'
/var/www/miq/vmdb/lib/vmdb/loggers/container_logger.rb:43:in `call'
/usr/share/ruby/logger.rb:582:in `format_message'
/usr/share/ruby/logger.rb:472:in `add'
/opt/manageiq/manageiq-gemset/gems/activerecord-session_store-1.1.3/lib/active_record/session_store/extension/logger_silencer.rb:38:in `add_with_threadsafety'
/opt/manageiq/manageiq-gemset/gems/activesupport-5.2.4.4/lib/active_support/logger.rb:27:in `block (2 levels) in broadcast'
/usr/share/ruby/logger.rb:534:in `warn'
/var/www/miq/vmdb/lib/vmdb/logging.rb:25:in `block (2 levels) in <class:LogProxy>'
/opt/manageiq/manageiq-gemset/bundler/gems/manageiq-providers-azure-e483ca2543bf/app/models/manageiq/providers/azure/inventory/collector/cloud_manager.rb:38:in `rescue in images'
/opt/manageiq/manageiq-gemset/bundler/gems/manageiq-providers-azure-e483ca2543bf/app/models/manageiq/providers/azure/inventory/collector/cloud_manager.rb:35:in `images'
/opt/manageiq/manageiq-gemset/bundler/gems/manageiq-providers-azure-e483ca2543bf/app/models/manageiq/providers/azure/inventory/parser/cloud_manager.rb:402:in `images'
/opt/manageiq/manageiq-gemset/bundler/gems/manageiq-providers-azure-e483ca2543bf/app/models/manageiq/providers/azure/inventory/parser/cloud_manager.rb:18:in `parse'
/var/www/miq/vmdb/app/models/manageiq/providers/inventory.rb:42:in `block in parse'
/var/www/miq/vmdb/app/models/manageiq/providers/inventory.rb:39:in `each'
/var/www/miq/vmdb/app/models/manageiq/providers/inventory.rb:39:in `parse'
/var/www/miq/vmdb/app/models/manageiq/providers/base_manager/refresher.rb:125:in `parse_targeted_inventory'
/var/www/miq/vmdb/app/models/manageiq/providers/base_manager/refresher.rb:92:in `block in refresh_targets_for_ems'
/opt/manageiq/manageiq-gemset/gems/more_core_extensions-4.3.0/lib/more_core_extensions/core_ext/benchmark/realtime_store.rb:20:in `realtime_store'
/opt/manageiq/manageiq-gemset/gems/more_core_extensions-4.3.0/lib/more_core_extensions/core_ext/benchmark/realtime_store.rb:56:in `realtime_block'
/var/www/miq/vmdb/app/models/manageiq/providers/base_manager/refresher.rb:91:in `refresh_targets_for_ems'
/var/www/miq/vmdb/app/models/manageiq/providers/base_manager/refresher.rb:41:in `block (2 levels) in refresh'
/opt/manageiq/manageiq-gemset/gems/more_core_extensions-4.3.0/lib/more_core_extensions/core_ext/benchmark/realtime_store.rb:20:in `realtime_store'
/opt/manageiq/manageiq-gemset/gems/more_core_extensions-4.3.0/lib/more_core_extensions/core_ext/benchmark/realtime_store.rb:62:in `realtime_block'
/var/www/miq/vmdb/app/models/manageiq/providers/base_manager/refresher.rb:41:in `block in refresh'
/var/www/miq/vmdb/app/models/manageiq/providers/base_manager/refresher.rb:31:in `each'
/var/www/miq/vmdb/app/models/manageiq/providers/base_manager/refresher.rb:31:in `refresh'
/var/www/miq/vmdb/app/models/manageiq/providers/base_manager/refresher.rb:11:in `refresh'
/var/www/miq/vmdb/app/models/ems_refresh.rb:71:in `block in refresh'
/var/www/miq/vmdb/app/models/ems_refresh.rb:70:in `each'
/var/www/miq/vmdb/app/models/ems_refresh.rb:70:in `refresh'
/var/www/miq/vmdb/app/models/miq_queue.rb:484:in `block in dispatch_method'
/usr/share/ruby/timeout.rb:93:in `block in timeout'
/usr/share/ruby/timeout.rb:33:in `block in catch'
/usr/share/ruby/timeout.rb:33:in `catch'
/usr/share/ruby/timeout.rb:33:in `catch'
/usr/share/ruby/timeout.rb:108:in `timeout'
/var/www/miq/vmdb/app/models/miq_queue.rb:482:in `dispatch_method'
/var/www/miq/vmdb/app/models/miq_queue.rb:459:in `block in deliver'
/var/www/miq/vmdb/app/models/user.rb:360:in `with_user_group'
/var/www/miq/vmdb/app/models/miq_queue.rb:459:in `deliver'
/var/www/miq/vmdb/app/models/miq_queue_worker_base/runner.rb:80:in `deliver_queue_message'
/var/www/miq/vmdb/app/models/miq_queue_worker_base/runner.rb:104:in `deliver_message'
/var/www/miq/vmdb/app/models/miq_queue_worker_base/runner.rb:122:in `block in do_work'
/var/www/miq/vmdb/app/models/miq_queue_worker_base/runner.rb:118:in `loop'
/var/www/miq/vmdb/app/models/miq_queue_worker_base/runner.rb:118:in `do_work'
/var/www/miq/vmdb/app/models/miq_worker/runner.rb:264:in `block in do_work_loop'
/var/www/miq/vmdb/app/models/miq_worker/runner.rb:261:in `loop'
/var/www/miq/vmdb/app/models/miq_worker/runner.rb:261:in `do_work_loop'
/var/www/miq/vmdb/app/models/miq_worker/runner.rb:113:in `run'
/var/www/miq/vmdb/app/models/miq_worker/runner.rb:95:in `start'
/var/www/miq/vmdb/lib/workers/bin/run_single_worker.rb:122:in `<main>'
[----] E, [2021-03-30T21:14:17.981115 #7:2b25bdd0597c] ERROR -- : MIQ(ManageIQ::Providers::Azure::CloudManager::Refresher#refresh) EMS: [test2], id: [5] Unable to perform refresh for the following targets:
[----] E, [2021-03-30T21:14:17.981189 #7:2b25bdd0597c] ERROR -- : MIQ(ManageIQ::Providers::Azure::CloudManager::Refresher#refresh)  --- ManageIQ::Providers::Azure::CloudManager [test2] id [5]
[----] I, [2021-03-30T21:14:18.134706 #7:2b25bdd0597c]  INFO -- : MIQ(ManageIQ::Providers::Azure::CloudManager::Refresher#refresh) Refreshing all targets...Complete
[----] E, [2021-03-30T21:14:18.134874 #7:2b25bdd0597c] ERROR -- : MIQ(MiqQueue#deliver) Message id: [1199757], Error: ["\xEF" from ASCII-8BIT to UTF-8]
[----] E, [2021-03-30T21:14:18.134951 #7:2b25bdd0597c] ERROR -- : [ManageIQ::Providers::BaseManager::Refresher::PartialRefreshError]: "\xEF" from ASCII-8BIT to UTF-8  Method:[block (2 levels) in <class:LogProxy>]
[----] E, [2021-03-30T21:14:18.135051 #7:2b25bdd0597c] ERROR -- : /var/www/miq/vmdb/app/models/manageiq/providers/base_manager/refresher.rb:67:in `refresh'
/var/www/miq/vmdb/app/models/manageiq/providers/base_manager/refresher.rb:11:in `refresh'
/var/www/miq/vmdb/app/models/ems_refresh.rb:71:in `block in refresh'
/var/www/miq/vmdb/app/models/ems_refresh.rb:70:in `each'
/var/www/miq/vmdb/app/models/ems_refresh.rb:70:in `refresh'
/var/www/miq/vmdb/app/models/miq_queue.rb:484:in `block in dispatch_method'
/usr/share/ruby/timeout.rb:93:in `block in timeout'
/usr/share/ruby/timeout.rb:33:in `block in catch'
/usr/share/ruby/timeout.rb:33:in `catch'
/usr/share/ruby/timeout.rb:33:in `catch'
/usr/share/ruby/timeout.rb:108:in `timeout'
/var/www/miq/vmdb/app/models/miq_queue.rb:482:in `dispatch_method'
/var/www/miq/vmdb/app/models/miq_queue.rb:459:in `block in deliver'
/var/www/miq/vmdb/app/models/user.rb:360:in `with_user_group'
/var/www/miq/vmdb/app/models/miq_queue.rb:459:in `deliver'
/var/www/miq/vmdb/app/models/miq_queue_worker_base/runner.rb:80:in `deliver_queue_message'
/var/www/miq/vmdb/app/models/miq_queue_worker_base/runner.rb:104:in `deliver_message'
/var/www/miq/vmdb/app/models/miq_queue_worker_base/runner.rb:122:in `block in do_work'
/var/www/miq/vmdb/app/models/miq_queue_worker_base/runner.rb:118:in `loop'
/var/www/miq/vmdb/app/models/miq_queue_worker_base/runner.rb:118:in `do_work'
/var/www/miq/vmdb/app/models/miq_worker/runner.rb:264:in `block in do_work_loop'
/var/www/miq/vmdb/app/models/miq_worker/runner.rb:261:in `loop'
/var/www/miq/vmdb/app/models/miq_worker/runner.rb:261:in `do_work_loop'
/var/www/miq/vmdb/app/models/miq_worker/runner.rb:113:in `run'
/var/www/miq/vmdb/app/models/miq_worker/runner.rb:95:in `start'
/var/www/miq/vmdb/lib/workers/bin/run_single_worker.rb:122:in `<main>'
[----] I, [2021-03-30T21:14:18.135130 #7:2b25bdd0597c]  INFO -- : MIQ(MiqQueue#delivered) Message id: [1199757], State: [error], Delivered in [11.536006695] seconds
[----] I, [2021-03-30T21:43:51.265421 #7:2b25bdd0597c]  INFO -- : MIQ(ManageIQ::Providers::Azure::CloudManager::RefreshWorker::Runner#config_out_of_date?) MIQ(ManageIQ::Providers::Azure::CloudManager::RefreshWorker::Runner) Configuration has changed, New TS: 2021-03-30 21:43:41 UTC, Old TS: 2021-03-30 21:14:06 UTC
[----] I, [2021-03-30T21:43:51.265523 #7:2b25bdd0597c]  INFO -- : MIQ(ManageIQ::Providers::Azure::CloudManager::RefreshWorker::Runner#heartbeat) MIQ(ManageIQ::Providers::Azure::CloudManager::RefreshWorker::Runner) Synchronizing configuration...
[----] I, [2021-03-30T21:43:51.386556 #7:2b25bdd0597c]  INFO -- : MIQ(ManageIQ::Providers::Azure::CloudManager::RefreshWorker::Runner#sync_config) ID [430], PID [7], GUID [6ad909fc-59ce-48c5-b5b4-e31f24c06793], Zone [default], Active Roles [automate,database_operations,ems_inventory,ems_operations,event,remote_console,reporting,scheduler,smartstate,user_interface,web_services], Assigned Roles [automate,database_operations,database_owner,ems_inventory,ems_operations,event,remote_console,reporting,scheduler,smartstate,user_interface,web_services], Configuration:
[----] I, [2021-03-30T21:43:51.386854 #7:2b25bdd0597c]  INFO -- : 
```

**Comment by agrare** [comment]
Ah perfect the right backtrace!  Thanks @evertmulder 

This looks like the same issue as https://github.com/ManageIQ/manageiq-providers-azure/issues/433

**Comment by agrare** [comment]
So that is coming from https://github.com/ManageIQ/manageiq-providers-azure/blob/e483ca2543bf/app/models/manageiq/providers/azure/inventory/collector/cloud_manager.rb#L38
It appears there is binary data coming back in the exception message from azure when listing all private images for the region.

Are you able to reproduce this often?

**Comment by evertmulder** [comment]
well in the containerized manageiq I did not have a successful refresh ever. The appliance works every time using the same azure subscription and sp.

**Comment by agrare** [comment]
Oh that's interesting I wasn't expecting that.  Do you see anything in the `azure.log` ?  Could you try `Base64.encode64(err.message)` so we can see what the exception message is

**Comment by evertmulder** [comment]
Yes the azure log give me a 400

```
[----] W, [2021-04-03T17:28:04.593942 #84103:2b203ff1996c]  WARN -- : RestClient.get "https://management.azure.com/subscriptions/3d594aa6-4176-4a12-a956-d9484702ab43/providers/Microsoft.Storage/storageAccounts?api-version=2017-10-01", "Accept"=>"application/json", "Authorization"=>"Bearer [FILTERED] ", "Content-Type"=>"application/json", "User-Agent"=>"rest-client/2.1.0 (linux-gnu x86_64) ruby/2.6.3p62"
[----] W, [2021-04-03T17:28:04.664990 #84103:2b203ff1996c]  WARN -- : # => 200 OK | application/json 1173 bytes, 0.07s
[----] W, [2021-04-03T17:28:04.671684 #84103:2b20471660ec]  WARN -- : RestClient.post "https://management.azure.com/subscriptions/3d594aa6-4176-4a12-a956-d9484702ab43/resourceGroups/cloud-shell-storage-westeurope/providers/Microsoft.Storage/storageAccounts/csb10037ffea12a499b/listKeys?api-version=2017-10-01", "", "Accept"=>"application/json", "Authorization"=>"Bearer [FILTERED] ", "Content-Length"=>"0", "Content-Type"=>"application/json", "User-Agent"=>"rest-client/2.1.0 (linux-gnu x86_64) ruby/2.6.3p62"
[----] W, [2021-04-03T17:28:04.780329 #84103:2b20471660ec]  WARN -- : # => 200 OK | application/json 288 bytes, 0.11s
[----] W, [2021-04-03T17:28:04.786832 #84103:2b20471660ec]  WARN -- : RestClient.get "https://csb10037ffea12a499b.blob.core.windows.net/?comp=list", "Accept"=>"*/*", "User-Agent"=>"rest-client/2.1.0 (linux-gnu x86_64) ruby/2.6.3p62", "auth_string"=>"true", "authorization"=>"SharedKey [FILTERED] ", "content-type"=>"", "x-ms-date"=>"Sat, 03 Apr 2021 17:28:04 GMT", "x-ms-version"=>"2016-05-31"
[----] W, [2021-04-03T17:28:04.873659 #84103:2b20471660ec]  WARN -- : # => 400 BadRequest | application/xml 266 bytes, 0.09s
```

I will try to get the `Base64.encode64(err.message)` but is a bit hard inside the container. (RO filesystem...)

**Comment by agrare** [comment]
That's perfect @evertmulder thank you, there are a couple of chars before the start of the XML doc: `\xEF\xBB\xBF<?xml version=\"1.0\"` that are forcing it to not be encoded with utf-8.

**Comment by agrare** [comment]
This can be closed when https://github.com/ManageIQ/azure-armrest/pull/406 is released

**Comment by agrare** [comment]
@evertmulder please update azure-armrest to v0.11.0 and retest when you get a chance, thanks!
