### ISSUE TITLE
Undefined method private_ip_address

### ISSUE THREAD

**Issue by djberg96** [ManageIQ/manageiq-providers-azure#82]
Saw this in the log today:

```
[----] E, [2017-06-22T10:44:55.429941 #82338:3fcfa103f7f4] ERROR -- : [NoMethodError]: undefined method `private_ip_address' for #<Azure::Armrest::Network::NetworkInterface::Properties::IpConfiguration::Properties:0x007f9f3303e9c0>
Did you mean?  private_ip_address_version  Method:[block (2 levels) in <class:LogProxy>]
[----] E, [2017-06-22T10:44:55.430104 #82338:3fcfa103f7f4] ERROR -- : /Users/dberger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/manageiq-providers-azure-add872d4adfc/app/models/manageiq/providers/azure/network_manager/refresh_parser.rb:393:in `parse_cloud_subnet_network_port'
/Users/dberger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/manageiq-providers-azure-add872d4adfc/app/models/manageiq/providers/azure/network_manager/refresh_parser.rb:401:in `block in parse_network_port'
/Users/dberger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/manageiq-providers-azure-add872d4adfc/app/models/manageiq/providers/azure/network_manager/refresh_parser.rb:400:in `map'
/Users/dberger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/manageiq-providers-azure-add872d4adfc/app/models/manageiq/providers/azure/network_manager/refresh_parser.rb:400:in `parse_network_port'
/Users/dberger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/manageiq-providers-azure-add872d4adfc/app/models/manageiq/providers/azure/network_manager/refresh_parser.rb:99:in `block in get_network_ports'
/Users/dberger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/manageiq-providers-azure-add872d4adfc/app/models/manageiq/providers/azure/refresh_helper_methods.rb:10:in `block in process_collection'
/Users/dberger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/manageiq-providers-azure-add872d4adfc/app/models/manageiq/providers/azure/refresh_helper_methods.rb:9:in `each'
/Users/dberger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/manageiq-providers-azure-add872d4adfc/app/models/manageiq/providers/azure/refresh_helper_methods.rb:9:in `process_collection'
/Users/dberger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/manageiq-providers-azure-add872d4adfc/app/models/manageiq/providers/azure/network_manager/refresh_parser.rb:99:in `get_network_ports'
/Users/dberger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/manageiq-providers-azure-add872d4adfc/app/models/manageiq/providers/azure/network_manager/refresh_parser.rb:33:in `ems_inv_to_hashes'
/Users/dberger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/manageiq-providers-azure-add872d4adfc/app/models/manageiq/providers/azure/network_manager/refresh_parser.rb:8:in `ems_inv_to_hashes'
/Users/dberger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/manageiq-providers-azure-add872d4adfc/app/models/manageiq/providers/azure/network_manager/refresher.rb:6:in `parse_legacy_inventory'
/Users/dberger/Repositories/manageiq-djberg96/app/models/ems_refresh/refreshers/ems_refresher_mixin.rb:146:in `block in parse_targeted_inventory'
/Users/dberger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/manageiq-gems-pending-23fd9dd038d3/lib/gems/pending/util/extensions/miq-benchmark.rb:11:in `realtime_store'
/Users/dberger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/manageiq-gems-pending-23fd9dd038d3/lib/gems/pending/util/extensions/miq-benchmark.rb:30:in `realtime_block'
/Users/dberger/Repositories/manageiq-djberg96/app/models/ems_refresh/refreshers/ems_refresher_mixin.rb:146:in `parse_targeted_inventory'
/Users/dberger/Repositories/manageiq-djberg96/app/models/ems_refresh/refreshers/ems_refresher_mixin.rb:87:in `block in refresh_targets_for_ems'
/Users/dberger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/manageiq-gems-pending-23fd9dd038d3/lib/gems/pending/util/extensions/miq-benchmark.rb:11:in `realtime_store'
/Users/dberger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/manageiq-gems-pending-23fd9dd038d3/lib/gems/pending/util/extensions/miq-benchmark.rb:30:in `realtime_block'
/Users/dberger/Repositories/manageiq-djberg96/app/models/ems_refresh/refreshers/ems_refresher_mixin.rb:86:in `refresh_targets_for_ems'
/Users/dberger/Repositories/manageiq-djberg96/app/models/ems_refresh/refreshers/ems_refresher_mixin.rb:24:in `block (2 levels) in refresh'
/Users/dberger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/manageiq-gems-pending-23fd9dd038d3/lib/gems/pending/util/extensions/miq-benchmark.rb:11:in `realtime_store'
/Users/dberger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/manageiq-gems-pending-23fd9dd038d3/lib/gems/pending/util/extensions/miq-benchmark.rb:30:in `realtime_block'
/Users/dberger/Repositories/manageiq-djberg96/app/models/ems_refresh/refreshers/ems_refresher_mixin.rb:24:in `block in refresh'
/Users/dberger/Repositories/manageiq-djberg96/app/models/ems_refresh/refreshers/ems_refresher_mixin.rb:14:in `each'
/Users/dberger/Repositories/manageiq-djberg96/app/models/ems_refresh/refreshers/ems_refresher_mixin.rb:14:in `refresh'
/Users/dberger/Repositories/manageiq-djberg96/app/models/manageiq/providers/base_manager/refresher.rb:9:in `refresh'
/Users/dberger/Repositories/manageiq-djberg96/app/models/ems_refresh.rb:97:in `block in refresh'
/Users/dberger/Repositories/manageiq-djberg96/app/models/ems_refresh.rb:96:in `each'
/Users/dberger/Repositories/manageiq-djberg96/app/models/ems_refresh.rb:96:in `refresh'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_queue.rb:328:in `block in deliver'
/Users/dberger/.rbenv/versions/2.4.1/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
/Users/dberger/.rbenv/versions/2.4.1/lib/ruby/2.4.0/timeout.rb:33:in `block in catch'
/Users/dberger/.rbenv/versions/2.4.1/lib/ruby/2.4.0/timeout.rb:33:in `catch'
/Users/dberger/.rbenv/versions/2.4.1/lib/ruby/2.4.0/timeout.rb:33:in `catch'
/Users/dberger/.rbenv/versions/2.4.1/lib/ruby/2.4.0/timeout.rb:108:in `timeout'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_queue.rb:324:in `deliver'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_queue_worker_base/runner.rb:107:in `deliver_queue_message'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_queue_worker_base/runner.rb:135:in `deliver_message'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_queue_worker_base/runner.rb:153:in `block in do_work'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_queue_worker_base/runner.rb:147:in `loop'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_queue_worker_base/runner.rb:147:in `do_work'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_worker/runner.rb:343:in `block in do_work_loop'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_worker/runner.rb:340:in `loop'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_worker/runner.rb:340:in `do_work_loop'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_worker/runner.rb:161:in `run'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_worker/runner.rb:135:in `start'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_worker/runner.rb:22:in `start_worker'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_worker.rb:345:in `block in start_runner_via_fork'
/Users/dberger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/nakayoshi_fork-0.0.3/lib/nakayoshi_fork.rb:24:in `fork'
/Users/dberger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/nakayoshi_fork-0.0.3/lib/nakayoshi_fork.rb:24:in `fork'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_worker.rb:343:in `start_runner_via_fork'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_worker.rb:338:in `start_runner'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_worker.rb:371:in `start'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_worker.rb:266:in `start_worker'
/Users/dberger/Repositories/manageiq-djberg96/app/models/mixins/per_ems_worker_mixin.rb:68:in `start_worker_for_ems'
/Users/dberger/Repositories/manageiq-djberg96/app/models/mixins/per_ems_worker_mixin.rb:46:in `block in sync_workers'
/Users/dberger/Repositories/manageiq-djberg96/app/models/mixins/per_ems_worker_mixin.rb:45:in `each'
/Users/dberger/Repositories/manageiq-djberg96/app/models/mixins/per_ems_worker_mixin.rb:45:in `sync_workers'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_server/worker_management/monitor.rb:53:in `block in sync_workers'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_server/worker_management/monitor.rb:50:in `each'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_server/worker_management/monitor.rb:50:in `sync_workers'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_server/worker_management/monitor.rb:22:in `monitor_workers'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_server.rb:346:in `block in monitor'
/Users/dberger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/manageiq-gems-pending-23fd9dd038d3/lib/gems/pending/util/extensions/miq-benchmark.rb:11:in `realtime_store'
/Users/dberger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/manageiq-gems-pending-23fd9dd038d3/lib/gems/pending/util/extensions/miq-benchmark.rb:30:in `realtime_block'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_server.rb:346:in `monitor'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_server.rb:368:in `block (2 levels) in monitor_loop'
/Users/dberger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/manageiq-gems-pending-23fd9dd038d3/lib/gems/pending/util/extensions/miq-benchmark.rb:11:in `realtime_store'
/Users/dberger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/manageiq-gems-pending-23fd9dd038d3/lib/gems/pending/util/extensions/miq-benchmark.rb:30:in `realtime_block'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_server.rb:368:in `block in monitor_loop'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_server.rb:367:in `loop'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_server.rb:367:in `monitor_loop'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_server.rb:250:in `start'
/Users/dberger/Repositories/manageiq-djberg96/lib/workers/evm_server.rb:27:in `start'
/Users/dberger/Repositories/manageiq-djberg96/lib/workers/evm_server.rb:48:in `start'
/Users/dberger/Repositories/manageiq-djberg96/lib/workers/bin/evm_server.rb:4:in `<main>'
```

**Comment by djberg96** [comment]
I'm seeing the failure specifically on a NIC with multiple configurations, e.g. IPv4 and IPv6. It's the second configuration (the IPv6 configuration) that doesn't have a `private_ip_address` property.

**Comment by jteehan** [comment]
Took a half a day but I think I figured it out.  The only way to get an IPV6 attached to a VM is to spin up an entire Load Balancer.  I'll paste the code under a separate pastebin or equivelent.

[----] E, [2017-07-25T17:05:11.235152 #21461:79b134] ERROR -- : MIQ(MiqQueue#deliver) Message id: [31243], Error: [undefined method `subnet' for #<Azure::Armrest::Network::NetworkInterface::Properties::IpConfiguration::Properties:0x0000000a025be8>]
[----] E, [2017-07-25T17:05:11.235323 #21461:79b134] ERROR -- : [EmsRefresh::Refreshers::EmsRefresherMixin::PartialRefreshError]: undefined method `subnet' for #<Azure::Armrest::Network::NetworkInterface::Properties::IpConfiguration::Properties:0x0000000a025be8>  Method:[rescue in deliver]
